[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
hex = "0.4.3"
serde_json = "1.0.145"
sha2 = "0.10.9"
shared = { version = "0.1.0", path = "../shared" }
uuid = { version = "1.19.0", features = ["v4", "fast-rng"] }
